
---CREATE TABLE CommodityRationingViewModel
CREATE TABLE "CommodityRationingView" (
"uniqueId"  TEXT NOT NULL COLLATE NOCASE ,
"quotasName"  TEXT ,
"fromDate"  TEXT  ,
"toDate"  TEXT,
"dataCenterOwnerIds"  TEXT,
"customerLevelIds" Text,
"customerActivityIds" Text,
"customerCategoryIds" Text,
"personnelIds" Text,
"quotasType" int,
PRIMARY KEY ("uniqueId" ASC));

--- CREATE TABLE Product_RationingViewModel
CREATE TABLE "Product_RationingView" (
"uniqueId"  TEXT NOT NULL COLLATE NOCASE ,
"quotasUniqueId"  TEXT ,
"productUniuqeId"  TEXT  ,
"productUnitUniuqeId"  TEXT,
"productCode"  TEXT,
"productName" Text,
"quantity" int,
PRIMARY KEY ("uniqueId" ASC));


--- CREATE TABLE DealerCommissionDataModel
CREATE TABLE "DealerCommissionData" (
"uniqueId"  TEXT NOT NULL COLLATE NOCASE ,
"CenterName"  TEXT  ,
"Year"  int ,
"Month"  int ,
"DealerCode"  TEXT  ,
"DealerName"  TEXT,
"SpaghettiTarget"  int,
"ShapedTarget"  int,
"LasagnaTarget"  int,
"NestTarget"  int,
"JumboTarget"  int,
"CakePowderTarget"  int,
"FlourTarget"  int,
"PottageTarget"  int,
"SpaghettiSales"  int,
"ShapedSales"  int,
"LasagnaSales"  int,
"NestSales"  int,
"JumboSales"  int,
"CakePowderSales"  int,
"FlourSales"  int,
"PottageSales"  int,
"SpaghettiAchive"  FLOAT,
"ShapedAchive"  FLOAT,
"LasagnaAchive"  FLOAT,
"NestAchive"  FLOAT,
"JumboAchive"  FLOAT,
"CakePowderAchive"  FLOAT,
"FlourAchive"  FLOAT,
"PottageAchive"  FLOAT,
"RankOnGlobal"  int,
"RankOnTeam"  int,
"SpaghettiPayment"  int,
"ShapedPayment"  int,
"LasagnaPayment"  int,
"NestPayment"  int,
"JumboPayment"  int,
"CakePowderPayment"  int,
"FlourPayment"  int,
"PottagePayment"  int,
"CoverageRatePayment"  int,
"HitRatePayment"  int,
"LpscPayment"  int,
"FinalPayment"  int,
PRIMARY KEY ("uniqueId" ASC));
