-- ----------------------------
-- FullEvc
-- ----------------------------
ALTER TABLE EVCHeaderSDS ADD COLUMN SupervisorName NVARCHAR(2048) NULL;
ALTER TABLE EVCHeaderSDS ADD COLUMN DealerName NVARCHAR(2048) NULL;
ALTER TABLE EVCHeaderSDS ADD COLUMN StockDCName NVARCHAR(2048) NULL;


ALTER TABLE DiscountCustomer ADD COLUMN CustCtgrName   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN CustActName	   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN CustLevelName  NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN CityName	   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN StateName	   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN DcName		   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN OwnerTypeName  NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN SalePathName   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN SaleAreaName   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN SaleZoneName   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN DistPathName   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN DistAreaName   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN DistZoneName   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN CountyName	   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN ExtraField1	   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN ExtraField2	   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN ExtraField3	   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN ExtraField4	   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN ExtraField5	   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN ExtraField6	   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN ExtraField7	   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN ExtraField8	   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN ExtraField9	   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN ExtraField10   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN ExtraField11   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN ExtraField12   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN ExtraField13   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN ExtraField14   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN ExtraField15   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN ExtraField16   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN ExtraField17   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN ExtraField18   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN ExtraField19   NVARCHAR(2048) NULL;
ALTER TABLE DiscountCustomer ADD COLUMN ExtraField20   NVARCHAR(2048) NULL;

ALTER TABLE DiscountProduct ADD COLUMN ManufacturerName NVARCHAR(2048) NULL;
ALTER TABLE DiscountProduct ADD COLUMN BrandName  NVARCHAR(2048) NULL;
ALTER TABLE DiscountProduct ADD COLUMN ShipTypeName  NVARCHAR(2048) NULL;

ALTER TABLE DiscountSellPayType ADD COLUMN PayTypeName NVARCHAR(2048) NULL;

CREATE TABLE IF NOT EXISTS  "main"."DiscountDisType" (
"Code"  INTEGER,
"Title"  NVARCHAR(2048)
);

CREATE TABLE IF NOT EXISTS  "main"."DiscountOrderType" (
"OrderTypeId"  INTEGER,
"OrderTypeName"  NVARCHAR(2048)
);
